### ISSUE TITLE
RateLimit Exceeded

### ISSUE THREAD

**Issue by sanderbrinkhuis** [cdklabs/cdk-appflow#107]
We are hitting rate limit exceeded, any suggestion on how to fix this.

Example from log: 
5:07:49 PM | CREATE_FAILED        | AWS::AppFlow::Flow      | SFtoGPActivityLice...ementaldevE55344D9
Resource handler returned message: "Error occurred during operation 'AWS::AppFlow::FlowToo Many Requests (Service: Appflow, Status Code: 429, Request ID: 1464ff79-0c0e-4957-9f33-dab5fdd50ebf)'." (RequestToken: ce34d169-2cbd-a30c-bd32-25cc6aaee837, HandlerErrorCode: GeneralServiceException)

**Comment by kozub** [comment]
Thank you @sanderbrinkhuis for creating this issue. Could you please share some details or steps that allow to reproduce this issue on our environment?

I also recommend to verify your account configuration. The issue might be related to service quota on your account. By default it is: 

```
Your AWS account has the following quotas related to Amazon AppFlow.

Number of flows per account: 1,000

Number of flow runs per month: 10 million

Number of concurrent flow runs at any time: 1000
```

**Comment by sanderbrinkhuis** [comment]
This is reaction from AWS support:
_"From the case notes I understand you are experiencing an error 'AWS::AppFlow::FlowToo Many Requests' while creating 92 appflows using CDK. Please feel free to elaborate or correct me if my understanding varies in any way.

As per the reference [1] this is a bug and workaround is to force the resources to be created in serial instead of in parallel, by making them depend on each other. Request you to kindly go through the reference document to find the process."_  

It seems to be a bug similar too:  [https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1095](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1095)

**Comment by kozub** [comment]
Hey, I check the issue and it looks as it is more related to CloudFormation and we are not able to fix it in cdk-appflow.
