### ISSUE TITLE
AppFlow - OnScheduleFlow - TriggerProps is required for Scheduled Trigger Type

### ISSUE THREAD

**Issue by remitache** [cdklabs/cdk-appflow#129]
Hi,

I am facing an issue when create a OnScheduleFlow using the CDK. 

```typescript
const flowGeneral = new OnScheduleFlow(this, 'overall-data-scheduled', {
        status:FlowStatus.ACTIVE,
        source: source,
        destination: new_destination,
        pullConfig:{
            mode: DataPullMode.INCREMENTAL,
            timestampField:"startDate"
        },
        mappings: [
            ...
        ],
        // schedule: events.Schedule.rate(Duration.days(1)),
        schedule: events.Schedule.cron({minute:"0", hour:"1", day:"*", month:"*"}),
        scheduleProperties:{
            offset:Duration.days(500),
        }        
    });
```
    
When I deploy the code above and then visualise the Flow from the Console UI, the flow trigger section display the following message:

> This flow's schedule cron expression is not supported by the UI. Contact support for more details.".
  
Then I try to save it and I get the following message:

> Update Flow request failed due to:[TriggerProps is required for Scheduled Trigger Type.]".

I cannot find anyway to specify the triggerProps from the code and assumed it was generated internally with the lib. Is there anything I am missing ?
    
Thanks

![Screenshot 2024-02-27 at 13 03 13](https://github.com/cdklabs/cdk-appflow/assets/1668072/17a6498e-f212-4f10-8f51-a8db4f999f2e)
![Screenshot 2024-02-27 at 13 03 19](https://github.com/cdklabs/cdk-appflow/assets/1668072/398906d7-4b07-45c5-ae93-11d2ecd2c7e6)

**Comment by rpawlaszek** [comment]
Hi @remitache, if I understand correctly then it is not an issue with the IaC, but a limitation in the UI. From the CFN/SDK/CDK you have more flexibility in setting up the schedules, than from the UI. That written, can you confirm that the flow behaves as expected after deployment?

**Comment by remitache** [comment]
Hi @rpawlaszek thanks for your answer. I confirm that the flow is working fine despite not displaying the schedule from the console.
