### ISSUE TITLE
Implement components for Mailchimp

### ISSUE THREAD

**Issue by remitache** [cdklabs/cdk-appflow#152]
Dear team. Thanks for the great work around this lib. I am currently trying to use additional connectors from the CDK, first one being mailchimp. It is currently not available, but I managed to write my own MailChimpConnectorProfile based on your library. Do you think it would be possible to merge it in to your next release? Or are you planning on releasing more ConnectorsProfile soon ?

Thanks

**Comment by kozub** [comment]
Hey @remitache! Thank you for creating this issue. We are more than happy to see community contribution to the project. Could you please create a PR with your changes and let us know if there is anything that we might help?

**Comment by remitache** [comment]
Hi @kozub , I have created the PR. I will probably be working on a few more connectors in the next weeks as I would need them. Happy to share them afterwards.

**Comment by psrebniak** [comment]
@remitache thanks for raising PR, I have few comments. 
Once it's solved I will test it and then we can merge, also happy to review and test other components as well.

**Comment by psrebniak** [comment]
@remitache I created PR to your branch with few fixes, please review if this makes sense for you and merge, then we can approve your PR.

**Comment by psrebniak** [comment]
Implemented in #154

**Comment by rpawlaszek** [comment]
Thanks @remitache for this contribution!
