### ISSUE TITLE
Add Google Ads API version 16

### ISSUE THREAD

**Issue by remitache** [cdklabs/cdk-appflow#227]
Dear team.

Google Ads API v14 is deprecated and will stop working in a couple of days:

https://developers.google.com/google-ads/api/docs/sunset-dates

Is there any plan on your side to update the AppFlow console to support higher version? At this stage we are unable to manually create connectors with API version above v14.

Thanks

**Comment by rpawlaszek** [comment]
Hi @remitache,

this goal of this library is to expose the CloudFormation resources in the form of L2 AWS CDK constructs. The question you have targets the actual Amazon AppFlow service and it is out of scope for the cdk-appflow library. 

For the time being what I can point you to as a potential direction (CDK-based and with a known functionality) is [this example of Amazon AppFlow custom connector](https://github.com/aws-samples/amazon-appflow-petstore-custom-connector-example).

I'm closing this issue for now and we can reopen once Amazon AppFlow has a managed connector with higher versions.

**Comment by rpawlaszek** [comment]
@remitache, please check the supported version for the GoogleAds connector. There should be v16 supported now.

**Comment by rpawlaszek** [comment]
Implemented by #245
