### ISSUE TITLE
Allow resource selection for the MicrosoftSharepointOnlineSource 

### ISSUE THREAD

**Issue by MarcDuQuesne** [cdklabs/cdk-appflow#27]
I am using this library to create a flow between a `MicrosoftSharepointOnlineSource `and an `S3Destination`. The flow in itself works; however, when creating a flow in the console, I can select which resources I want to create a flow for (i.e. a document 'subdirectory'). Unless I am mistaken, this feature is not supported by the library.

I am unsure how this works, but I noticed the `MicrosoftSharepointOnlineObject `does contain a list of drive ids, but no item ids.

**Comment by psrebniak** [comment]
Hi @MarcDuQuesne 
Thanks for raising the issue. 
I tested it and you can pass `drives/${driveID}/items/${itemID}` as `MicrosoftSharepointOnlineObject` `drives` property. 
As this might be misleading, I created extra property `entities` that will replace deprecated `drives` in next release and added two examples: 
- `drives/${driveID}`
- `drives/${driveID}/items/${itemID}`

Hope that helps
