### ISSUE TITLE
Add support to create MicrosoftSharepointOnlineConnectorProfile for an app registered without an user

### ISSUE THREAD

**Issue by MarcDuQuesne** [cdklabs/cdk-appflow#28]
The `MicrosoftSharepointOnlineConnectorProfile `requires a combination of optional parameters: an endpoint, an access token, and a flow that contains the client ID and secret alongside a refresh token. It's not clear to me which combinations of these parameters is accepted (e.g. only the access token could be enough), and I suspect that only authorization on behalf of a user is supported.

It might be worth noting that when we get an access token from our endpoint, no refresh token is sent back. See the response details [here](https://learn.microsoft.com/en-us/graph/auth-v2-service?tabs=http) - the credentials we got are not bound to a user (I see that the refresh token is indeed included in the [response ](https://learn.microsoft.com/en-us/graph/auth-v2-service?tabs=http)in this case).

in the console, only the client id and secret are needed and they can be generated to obtain access without a user. Ideally, this should be possible in the construct as well.

**Comment by MarcDuQuesne** [comment]
It might be worth noting that when we get an access token from our endpoint, no refresh token is sent back. See the response details [here](https://learn.microsoft.com/en-us/graph/auth-v2-service?tabs=http) - the credentials we got are not bound to a user.

**Comment by MarcDuQuesne** [comment]
Adding the extra scope does not help - it only works when working on credentials meant to be used on behalf of the user:

> The [offline_access scope](https://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess) gives your app access to resources on behalf of the user for an extended time.

at the moment this remains thus an open issue.

**Comment by rpawlaszek** [comment]
Hi @MarcDuQuesne. Amazon AppFlow natively supports only user-based identities and works only with the Refresh Token Grant Flow for re-generating the access token. It doesn't enable native service principal based token re-generation (that relies on the Client Credentials Flow). 

I'm assuming here that you'd like to use service principal. Is that the case?

**Comment by MarcDuQuesne** [comment]
that is correct; I understand this is a limitation of Appflow and not this library. For my case, I can investigate (as you suggested) if we can create a dedicated 'user' and would appreciate it if you could relay this feature request to the Amazon Appflow team (or point me to where I can do it myself).

**Comment by rpawlaszek** [comment]
Thanks for the confirmation. As of now we cannot commit to adding the functionality to this library, so I'm closing this thread, but if things change - we can reopen.
