### ISSUE TITLE
Flow Time Updater lambda produces invalid scheduled rate expressions

### ISSUE THREAD

**Issue by blimmer** [cdklabs/cdk-appflow#334]
When creating an `OnScheduleFlow`, the flow time updater produces cron expressions that aren't compatible with the AppFlow API expectations.

According to [the docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appflow-flow-scheduledtriggerproperties.html#aws-properties-appflow-flow-scheduledtriggerproperties-properties), they require rate expressions that look like `rate(5minutes)`.

However, the custom resource lambda is not producing rates that look like this. With an input like `rate(1 day)` (which is what CDK events produce from `Schedule.rate(Duration.days(1))`, the lambda produces an output of `rate(1 days)`. This is close (it pluralized `day` -> `days`), but the space needs to be removed.

I haven't validated if the flow actually runs, but my assumption is that it does not due to this message in the UI:

![Screenshot 2024-09-09 at 11 05 38](https://github.com/user-attachments/assets/4e5d7222-b0e5-42c6-80ff-b5241a2380e6)

PS: thank you for this construct - it has been immensely helpful!

**Comment by blimmer** [comment]
If folks need to work around this in the meantime, you can force an override like this:

```ts
const coreReportFlow = new OnScheduleFlow(this, 'GA4CoreReportFlow', {
  // .. truncated ..
});

// Work around https://github.com/cdklabs/cdk-appflow/issues/334
// This could be removed if my PR to fix upstream is merged: https://github.com/cdklabs/cdk-appflow/pull/335
const ga4CfnFlow = this.node.findChild('GA4CoreReportFlow').node.findChild('GA4CoreReportFlow') as CfnFlow;
(ga4CfnFlow.triggerConfig as any).triggerProperties.scheduleExpression = 'rate(1days)';
```

You'll need to update:
- `GA4CoreReportFlow` to whatever `id` you're using for your `OnScheduleFlow`
- `rate(1days)` to whatever rate you're using

**Comment by rpawlaszek** [comment]
Hi @blimmer. Thanks for identifying and moving forward with addressing the issue! Although it was not affecting the functionality, this indeed from is not what we want from the UI/UX perspective. I will look into the PR shortly!

**Comment by rpawlaszek** [comment]
Hi @blimmer. There's been an issue with the publishing pipeline. I'll close this issue once we get the changes published.
