### ISSUE TITLE
Glue Database Role is too Permissive

### ISSUE THREAD

**Issue by blimmer** [cdklabs/cdk-appflow#336]
Currently, the role created for the Glue integration allows access to all glue resources: https://github.com/cdklabs/cdk-appflow/blob/f8dbccc7830405799761b41ef97e567a261d55ab/src/s3/destination.ts#L146-L185

It would be better if this were limited to the database specified instead of `*`.

**Comment by kozub** [comment]
Hey @blimmer! 
Thank you fro creating this issue. I believe it make sense to add it. Let me investigate.

**Comment by rpawlaszek** [comment]
@blimmer @kozub, please take a look at [the PR created](https://github.com/cdklabs/cdk-appflow/pull/357). Right now the default role's permissions bound it to the database and table(s) it's intended to work with. Additionally, now the users can set a custom role if necessary.
