### ISSUE TITLE
ScheduleProperties interface exposes unused properties

### ISSUE THREAD

**Issue by blimmer** [cdklabs/cdk-appflow#345]
The `ScheduleProperties` interface exposes `offset` and `timezone` properties that aren't used anywhere in the codebase. This is misleading and could confuse end-users. We should remove them.

**Comment by blimmer** [comment]
The problem is that, even if the user passes these variables, they not included in the template.

The issue lies here: https://github.com/cdklabs/cdk-appflow/blob/3d6ca5a4218f0e9ce84330921fe01f31dc9d9954/src/core/flows/flow-base.ts#L289-L309

This method strips those values, so they never make it to the template.

I added a failing test here to show that the properties don't make it to the template: https://github.com/cdklabs/cdk-appflow/pull/352

We should either:

1. Update the logic to pass timezone and offset; or,
2. Remove them, since it's misleading that we accept the properties but never pass them along to the template.

**Comment by rpawlaszek** [comment]
Agreed. My proposition is to:

- include the offset as it does have an effect
- not include the timezone as it does not.

This includes adding the missing line `scheduleOffset: props.properties?.offset?.toSeconds()` here: https://github.com/cdklabs/cdk-appflow/blob/3d6ca5a4218f0e9ce84330921fe01f31dc9d9954/src/core/flows/flow-base.ts#L299-L308
