### ISSUE TITLE
"Bump the dependency versions of aws-cdk-lib

### ISSUE THREAD

**Issue by MarcDuQuesne** [cdklabs/cdk-appflow#35]
The latest version of the aws-cdk-lib is 2.110.0 as of date.
Among the dependencies for the library, I see  `@aws-cdk/aws-glue-alpha@"2.84.0-alpha.0" `. 

Would it be possible to bump this dependency version? in the same project, we are using one of the latest versions of AuroraPostgresEngineVersion (15.x), and I'd like to downgrade this.

**Comment by rpawlaszek** [comment]
Hi @MarcDuQuesne. Picking this up as the next step.
