### ISSUE TITLE
`jest` version is incompatible with Typescript 5.x

### ISSUE THREAD

**Issue by blimmer** [cdklabs/cdk-appflow#353]
Every time tests run, we get this error:

```shell
$ npx projen test test/core/flows/on-demand-flow.test.ts
👾 test | jest --passWithNoTests --updateSnapshot test/core/flows/on-demand-flow.test.ts
ts-jest[versions] (WARN) Version 5.6.2 of typescript installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=3.8.0 <5.0.0-0). Please do not report issues in ts-jest if you are using unsupported versions.
```

You can also see the invalid dependency when you run `yarn` to install deps:

```shell
warning " > ts-jest@27.1.5" has incorrect peer dependency "typescript@>=3.8 <5.0".
```

`projen` doesn't upgrade the version of `jest` when it run dependency updates, so we need to do this manually.

**Comment by rpawlaszek** [comment]
Thank you @blimmer for looking into this! 

As with [projen](https://github.com/projen/projen) *"synthesized files should never be manually edited"* let's use [`jestVersion`](https://projen.io/docs/api/javascript/?_highlight=jestversion#projen.javascript.JestOptions.property.jestVersion) directly in `.projenrc.ts`.
