### ISSUE TITLE
Filetype Parquet needs to be upper case

### ISSUE THREAD

**Issue by thomasProgress** [cdklabs/cdk-appflow#374]
Deployment fails when using S3OutputFileType.PARQUET. 

The enum definition for PARQUET = "Parquet" needs to be change to "PARQUET" according to the docs  https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appflow-flow-s3outputformatconfig.html#cfn-appflow-flow-s3outputformatconfig-filetype

**Comment by psrebniak** [comment]
Hi @thomasProgress 
Could you please check what version you use and share full error?

**Comment by thomasProgress** [comment]
using version 0.1.0

code looks like:
`
    new appflow.OnDemandFlow(scope, `OnDemandFlow`, {
      name: `flowName`,
      source: new appflow.SalesforceSource({
        profile: props.connectionProfile,
        object: props.sObject,
        dataTransferApi: appflow.SalesforceDataTransferApi.AUTOMATIC,
        enableDynamicFieldUpdate: true,
        includeDeletedRecords: true,
      }),
      destination: new appflow.S3Destination({
        location: {
          bucket: props.s3Bucket,
          prefix: `bucket-backup`,
        },
        formatting: {
          fileType: appflow.S3OutputFileType.PARQUET,
          filePrefix: {
            type: appflow.S3OutputFilePrefixType.FILENAME,
            hierarchy: [
              appflow.S3OutputFilePrefixHierarchy.SCHEMA_VERSION,
              appflow.S3OutputFilePrefixHierarchy.EXECUTION_ID,
            ],
          },
          aggregation: {
            type: appflow.S3OutputAggregationType.NONE,
          },
          preserveSourceDataTypes: true,
        },
      }),
      mappings: [appflow.Mapping.mapAll()],
    });
  }
`

**Error message:**

6:30:08 AM | UPDATE_FAILED        | AWS::AppFlow::Flow          | CaseOnDemandFlow/CaseOnDemandFlow
Properties validation failed for resource CaseOnDemandFlow208123BD with message:
#/DestinationFlowConfigList/0/DestinationConnectorProperties/S3/S3OutputFormatConfig/FileType: #: only 1 subschema matches out of 2
#/DestinationFlowConfigList/0/DestinationConnectorProperties/S3/S3OutputFormatConfig/FileType: failed validation constraint for keyword [enum]
6:30:08 AM | UPDATE_FAILED        | AWS::AppFlow::Flow          | Field_History__cOn...ory__cOnDemandFlow
Properties validation failed for resource FieldHistorycOnDemandFlowBF6FA0A1 with message:
#/DestinationFlowConfigList/0/DestinationConnectorProperties/S3/S3OutputFormatConfig/FileType: #: only 1 subschema matches out of 2
#/DestinationFlowConfigList/0/DestinationConnectorProperties/S3/S3OutputFormatConfig/FileType: failed validation constraint for keyword [enum]
6:30:08 AM | UPDATE_FAILED        | AWS::AppFlow::Flow          | LeadOnDemandFlow/LeadOnDemandFlow
Properties validation failed for resource LeadOnDemandFlow3ACB8C49 with message:
#/DestinationFlowConfigList/0/DestinationConnectorProperties/S3/S3OutputFormatConfig/FileType: #: only 1 subschema matches out of 2
#/DestinationFlowConfigList/0/DestinationConnectorProperties/S3/S3OutputFormatConfig/FileType: failed validation constraint for keyword [enum]
6:30:08 AM | UPDATE_ROLLBACK_IN_P | AWS::CloudFormation::Stack  | SfdcBackupStack

**Section of CF Template**
`
FieldHistorycOnDemandFlowBF6FA0A1:
    Type: AWS::AppFlow::Flow
    Properties:
      DestinationFlowConfigList:
        - ConnectorType: S3
          DestinationConnectorProperties:
            S3:
              BucketName:
                Ref: SfdcBackupBucket2B87F73E
              BucketPrefix: sfdc-field-history-backup
              S3OutputFormatConfig:
                AggregationConfig:
                  AggregationType: None
                FileType: Parquet
                PrefixConfig:
                  PathPrefixHierarchy:
                    - SCHEMA_VERSION
                    - EXECUTION_ID
                  PrefixType: FILENAME
                PreserveSourceDataTyping: true
      FlowName: sfdc-field-history-backup
      MetadataCatalogConfig:
        GlueDataCatalog:
          DatabaseName:
            Ref: SfdcBackupGlueDatabase1E95D7A1
          RoleArn:
            Fn::GetAtt:
              - FieldHistorycOnDemandFlowGlueAccessRole8D5D01E9
              - Arn
          TablePrefix: sfdc-field-history-backup
      SourceFlowConfig:
        ConnectorProfileName: SalesforceStaging
        ConnectorType: Salesforce
        SourceConnectorProperties:
          Salesforce:
            DataTransferApi: AUTOMATIC
            EnableDynamicFieldUpdate: true
            IncludeDeletedRecords: true
            Object: Field_History__c
      Tasks:
        - ConnectorOperator:
            Salesforce: NO_OP
          SourceFields: []
          TaskProperties:
            - Key: EXCLUDE_SOURCE_FIELDS_LIST
              Value: "[]"
          TaskType: Map_all
      TriggerConfig:
        TriggerType: OnDemand
`

**Comment by psrebniak** [comment]
@thomasProgress I was not able to reproduce your issue, `S3OutputFileType` is correctly defined in file `src/s3/destination.ts:45`. 

Please provide minimal reproducible code, you can base on this snippet: 

```
const source = new SalesforceSource({
  profile: profile,
  object: 'Contact',
  dataTransferApi: SalesforceDataTransferApi.AUTOMATIC,
  enableDynamicFieldUpdate: true,
  includeDeletedRecords: true,
});

const bucket = new Bucket(stack, 'TestBucket', {
  autoDeleteObjects: true,
  removalPolicy: RemovalPolicy.DESTROY,
});

const destination = new S3Destination({
  location: { bucket },
  formatting: {
    fileType: S3OutputFileType.PARQUET,
    filePrefix: {
      type: S3OutputFilePrefixType.FILENAME,
      hierarchy: [
        S3OutputFilePrefixHierarchy.SCHEMA_VERSION,
        S3OutputFilePrefixHierarchy.EXECUTION_ID,
      ],
    },
    aggregation: { type: S3OutputAggregationType.NONE },
    preserveSourceDataTypes: true,
  },
});

new OnDemandFlow(stack, 'OnDemandFlow', {
  source: source,
  destination: destination,
  mappings: [Mapping.mapAll()],
});
```

When you pasting the sourcecode / templates, please make sure you to include it in source block with proper formatting.

**Comment by psrebniak** [comment]
@thomasProgress  ok, I see where the problem is - fix is coming
