### ISSUE TITLE
Add SalesforceDataTransferApi settings to source like how it's done in destination

### ISSUE THREAD

**Issue by sanderbrinkhuis** [cdklabs/cdk-appflow#60]
You need this setting if you want consistent output

export enum SalesforceDataTransferApi {

  AUTOMATIC = 'AUTOMATIC',
  BULKV2 = 'BULKV2',
  REST_SYNC = 'REST_SYNC'
}

See: https://docs.aws.amazon.com/appflow/latest/userguide/salesforce.html and then this part:
If you choose this option, be aware that each of the potential Salesforce APIs structures data differently. For recurring flows, the data output might vary from one flow run to the next. For example, if a flow runs daily, it might use REST API on one day to transfer 900 records, and it might use Bulk API 2.0 on the next day to transfer 1,100 records. For each of these runs, the respective Salesforce API formats the data differently. Some of the differences include how dates are formatted and how null values are represented.

**Comment by psrebniak** [comment]
Hi @sanderbrinkhuis
Thanks for raising the issue, PR is ready for a review, I expect this will be merged&released this week.

**Comment by sanderbrinkhuis** [comment]
Thanks for the speed for resolving the issue!

**Comment by psrebniak** [comment]
@sanderbrinkhuis new version is now released
