### ISSUE TITLE
A valid refreshToken is needed to create a MicrosoftSharepointOnlineConnectorProfile

### ISSUE THREAD

**Issue by MarcDuQuesne** [cdklabs/cdk-appflow#90]
This code:

```

    const profile = new MicrosoftSharepointOnlineConnectorProfile(this, 'TestProfile', {
      oAuth: {
        accessToken:
          SecretValue.unsafePlainText(accessToken),
      },
    });
```

produces:

`1 validation error detected: Value 'Error authenticating to connector: Failed to validate Connection while attempting "ValidateCredentials with CustomConnector" with connector failure Encountered authentication error while retrieving metadata. Error details: Status Code: 400 : {"error":"invalid_grant","error_description":"AADSTS9002313: Invalid request. Request is malformed or invalid. Trace ID: ** Correlation ID: ** Timestamp: 2024-01-24 15:24:27Z","error_codes":[9002313],"timestamp":"2024-01-24 15:24:27Z","trace_id":"***","correlation_id":***","error_uri":"https://login.microsoftonline.com/error?code=9002313"} {requestUri=https://login.microsoftonline.com/common/oauth2/v2.0/token, instanceUrl=null} (Service: null; Status Code: 400; Error Code: Client; Request ID: null; Proxy: null) (Service: null; Status Code: 400; Error Code: Client; Request ID: null; Proxy: null) (Service: Appflow, Status Code: 401, Request ID: ****)' at 'statusMessage' failed to satisfy constraint: Member must have length less than or equal to 1024`

In principle an access token is all that is needed for a valid connection (while valid); no refresh token should be needed when creating a profile. Currenly the only way of creating a profile via the cdk is to provide a valid refresh token. Note that an **invalid** one produces the same (misleading) error message (regardless of the length of said string).

The underlying problem I am trying to address: I am exploring solutions to allow credentials for non-user principals to be used with a solution based on appflow deployed via a cdk pipeline to a set of accounts I do not have direct access to; one suggestion I got was to create a custom lambda to refresh the token instead of relying on appflow to do it. This might well work, but at the moment I still need to create the profile by hand.

**Comment by rpawlaszek** [comment]
@MarcDuQuesne, I've just run a test with a valid accessToken (for a test user) and it went through successfully, that is:
- the MS SharePoint Online Connector Profile was created
- the flow execution with that connector profile completed successfully

Could you verify if the tenant you have is indeed `common`? The token requests are tenant-specific, and if yours isn't `common` then you have to add a specific token endpoint to the Connector Profile as:

```typescript
    declare const tenantId: string;

    const profile = new MicrosoftSharepointOnlineConnectorProfile(this, 'TestProfile', {
      oAuth: {
        accessToken: SecretValue.unsafePlainText(accessToken),
        endpoints: {
          token: MicrosoftSharepointOnlineTokenUrlBuilder.buildTokenUrl(tenantId),
        }
      },
    });
```

**Comment by rpawlaszek** [comment]
An update. I've just created a test stack with the definition as in the original question (that is: without the `endpoints` property) and the deployment went through successfully again. I cannot, unfortunately, reproduce the error on my end.

**Comment by rpawlaszek** [comment]
@MarcDuQuesne, I'm closing this issue due to the inactivity, but please reopen if you have any additional input.
